### ISSUE TITLE
Activity Tracker & Automatically Assign AWOL

### ISSUE THREAD

**Issue by Uncle-Sagbag** [Uncle-Sagbag/Kakapo#17]
In order to better keep track of activity, the Kakapo bot should take note of the last days users were active. Once a day, the Kakapo would take note of every user's voice channel activity and text channel activity.

There are multiple ways of doing this.  Feel free to suggest a new method, I am not confident in my own described below.

Here is my method. Keep track of two events: when an operator sends a message and when a operator joins a voice channel. When a operator initiates either of these events, the Kakapo bot should add their user ID and the date this event happened to a dictionary. Let's call this dictionary `inactivity_dict` which is kept in a separate file called inactivity_dict.py. Each time either event is occurring, the bot will check the user's ID against `inactivity_dict` to see if they're already there. If they're already there, their date of activity will be updated. If they are not there, their user ID and last date of activity will be added.

Make sure `inactivity_dict.py` is NOT pushed to the repo. Add it to the `.gitignore` file.

Every 7 days, the bot will check the `inactivity_dict`. If it finds an operator whose last date of activity is longer than 40 days ago, they will receive the AWOL role.

This should only affect users with Operator role. This means Bots and Combat Service Support will be ignored by this system.

**Comment by Pickle423** [comment]
I've uploaded a version of this. Rather than persistent storage, I've just made it a dictionary stored in the same file. I don't foresee us needing to reload this all that often, you can change the storage method if you really want though. I just figured since we don't kill the bot, and instead hot reload individual modules, it's unnecessary to add the complexity of persistently storing the dictionary.

Right now, if a person has the operative role, and has never had any activity recorded at all once the 7 day loop comes up, they will be given the AWOL role. People with activity going back more than 40 days will also be assigned the AWOL role.

It's not exactly what is described here, you can make changes as you see fit, I think this is fine and works.

**Comment by Uncle-Sagbag** [comment]
Persistent storage is necessary in most cases because the bot is killed to pull new changes from master. Would the latest implementation work if the bot is killed every 2-3 months? That's how often we update master.

Since it just checks every person's activity every 7 days, it seems like there is nothing to store. Would this be correct?

**Comment by Uncle-Sagbag** [comment]
Deprecated due to change of vision. We do not care about AWOLs anymore.
